<?php

/**
 * This is the model base class for the table "work_order_history".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "WorkOrderHistory".
 *
 * Columns in table "work_order_history" available as properties of the model,
 * followed by relations of table "work_order_history" available as properties of the model.
 *
 * @property integer $id
 * @property integer $work_order
 * @property integer $terminal
 * @property string $params
 * @property string $work_order_reception_date
 * @property string $work_order_completion_date
 *
 * @property WorkOrder $workOrder
 */
abstract class BaseWorkOrderHistory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'work_order_history';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'WorkOrderHistory|WorkOrderHistories', $n);
	}

	public static function representingColumn() {
		return 'params';
	}

	public function rules() {
		return array(
			array('work_order, terminal, params', 'required'),
			array('work_order, terminal', 'numerical', 'integerOnly'=>true),
			array('work_order_reception_date, work_order_completion_date', 'safe'),
			array('work_order_reception_date, work_order_completion_date', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, work_order, terminal, params, work_order_reception_date, work_order_completion_date', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'workOrder' => array(self::BELONGS_TO, 'WorkOrder', 'work_order'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'work_order' => null,
			'terminal' => Yii::t('app', 'Terminal'),
			'params' => Yii::t('app', 'Params'),
			'work_order_reception_date' => Yii::t('app', 'Work Order Reception Date'),
			'work_order_completion_date' => Yii::t('app', 'Work Order Completion Date'),
			'workOrder' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('work_order', $this->work_order);
		$criteria->compare('terminal', $this->terminal);
		$criteria->compare('params', $this->params, true);
		$criteria->compare('work_order_reception_date', $this->work_order_reception_date, true);
		$criteria->compare('work_order_completion_date', $this->work_order_completion_date, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}