<?php

/**
 * This is the model base class for the table "user_api".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "UserApi".
 *
 * Columns in table "user_api" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $name
 * @property string $surname
 *
 */
abstract class BaseUserApi extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user_api';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'UserApi|UserApis', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password', 'required'),
			array('username, name', 'length', 'max'=>50),
			array('password, surname', 'length', 'max'=>255),
			array('name, surname', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, name, surname', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'name' => Yii::t('app', 'Name'),
			'surname' => Yii::t('app', 'Surname'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('surname', $this->surname, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}