<?php

/**
 * This is the model base class for the table "free_zone".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FreeZone".
 *
 * Columns in table "free_zone" available as properties of the model,
 * followed by relations of table "free_zone" available as properties of the model.
 *
 * @property integer $fz_id
 * @property integer $initial_min
 * @property integer $initial_hour
 * @property integer $initial_dom
 * @property integer $initial_dow
 * @property integer $initial_month
 * @property integer $final_min
 * @property integer $final_hour
 * @property integer $final_dom
 * @property integer $final_dow
 * @property integer $final_month
 *
 * @property BssPlan[] $bssPlans
 */
abstract class BaseFreeZone extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'free_zone';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FreeZone|FreeZones', $n);
	}

	public static function representingColumn() {
		return 'fz_id';
	}

	public function rules() {
		return array(
			array('initial_min, initial_hour, initial_dom, initial_dow, initial_month, final_min, final_hour, final_dom, final_dow, final_month', 'numerical', 'integerOnly'=>true),
			array('initial_min, initial_hour, initial_dom, initial_dow, initial_month, final_min, final_hour, final_dom, final_dow, final_month', 'default', 'setOnEmpty' => true, 'value' => null),
			array('fz_id, initial_min, initial_hour, initial_dom, initial_dow, initial_month, final_min, final_hour, final_dom, final_dow, final_month', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bssPlans' => array(self::HAS_MANY, 'BssPlan', 'fz'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fz_id' => Yii::t('app', 'Fz'),
			'initial_min' => Yii::t('app', 'Initial Min'),
			'initial_hour' => Yii::t('app', 'Initial Hour'),
			'initial_dom' => Yii::t('app', 'Initial Dom'),
			'initial_dow' => Yii::t('app', 'Initial Dow'),
			'initial_month' => Yii::t('app', 'Initial Month'),
			'final_min' => Yii::t('app', 'Final Min'),
			'final_hour' => Yii::t('app', 'Final Hour'),
			'final_dom' => Yii::t('app', 'Final Dom'),
			'final_dow' => Yii::t('app', 'Final Dow'),
			'final_month' => Yii::t('app', 'Final Month'),
			'bssPlans' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fz_id', $this->fz_id);
		$criteria->compare('initial_min', $this->initial_min);
		$criteria->compare('initial_hour', $this->initial_hour);
		$criteria->compare('initial_dom', $this->initial_dom);
		$criteria->compare('initial_dow', $this->initial_dow);
		$criteria->compare('initial_month', $this->initial_month);
		$criteria->compare('final_min', $this->final_min);
		$criteria->compare('final_hour', $this->final_hour);
		$criteria->compare('final_dom', $this->final_dom);
		$criteria->compare('final_dow', $this->final_dow);
		$criteria->compare('final_month', $this->final_month);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}