<?php

/**
 * This is the model base class for the table "file_downloader_status".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FileDownloaderStatus".
 *
 * Columns in table "file_downloader_status" available as properties of the model,
 * followed by relations of table "file_downloader_status" available as properties of the model.
 *
 * @property integer $id
 * @property string $literal
 *
 * @property FileDownloaderData[] $fileDownloaderDatas
 */
abstract class BaseFileDownloaderStatus extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'file_downloader_status';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FileDownloaderStatus|FileDownloaderStatuses', $n);
	}

	public static function representingColumn() {
		return 'literal';
	}

	public function rules() {
		return array(
			array('literal', 'required'),
			array('literal', 'length', 'max'=>255),
			array('id, literal', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'fileDownloaderDatas' => array(self::HAS_MANY, 'FileDownloaderData', 'status'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'literal' => Yii::t('app', 'Literal'),
			'fileDownloaderDatas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('literal', $this->literal, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}