<?php

/**
 * This is the model base class for the table "quota_extra_traffic_type".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuotaExtraTrafficType".
 *
 * Columns in table "quota_extra_traffic_type" available as properties of the model,
 * followed by relations of table "quota_extra_traffic_type" available as properties of the model.
 *
 * @property integer $id
 * @property string $literal
 *
 * @property QuotaExtra[] $quotaExtras
 * @property QuotaExtraHistory[] $quotaExtraHistories
 */
abstract class BaseQuotaExtraTrafficType extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'quota_extra_traffic_type';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuotaExtraTrafficType|QuotaExtraTrafficTypes', $n);
	}

	public static function representingColumn() {
		return 'literal';
	}

	public function rules() {
		return array(
			array('literal', 'required'),
			array('literal', 'length', 'max'=>255),
			array('id, literal', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'quotaExtras' => array(self::HAS_MANY, 'QuotaExtra', 'traffic_type'),
			'quotaExtraHistories' => array(self::HAS_MANY, 'QuotaExtraHistory', 'traffic_type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'literal' => Yii::t('app', 'Literal'),
			'quotaExtras' => null,
			'quotaExtraHistories' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('literal', $this->literal, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}