<?php

/**
 * This is the model base class for the table "quota_profile".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuotaProfile".
 *
 * Columns in table "quota_profile" available as properties of the model,
 * followed by relations of table "quota_profile" available as properties of the model.
 *
 * @property integer $quota_profile_id
 * @property string $upload_quota
 * @property string $total_quota
 * @property integer $sla_nominal
 * @property integer $sla_upload_exceded
 * @property integer $sla_total_exceded
 *
 * @property BssPlan[] $bssPlans
 */
abstract class BaseQuotaProfile extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'quota_profile';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuotaProfile|QuotaProfiles', $n);
	}

	public static function representingColumn() {
		return 'quota_profile_id';
	}

	public function rules() {
		return array(
			array('upload_quota, total_quota, sla_nominal, sla_upload_exceded, sla_total_exceded', 'required'),
			array('sla_nominal, sla_upload_exceded, sla_total_exceded', 'numerical', 'integerOnly'=>true),
			array('upload_quota, total_quota', 'length', 'max'=>20),
			array('quota_profile_id, upload_quota, total_quota, sla_nominal, sla_upload_exceded, sla_total_exceded', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'bssPlans' => array(self::HAS_MANY, 'BssPlan', 'quota_profile'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'quota_profile_id' => Yii::t('app', 'Quota Profile'),
			'upload_quota' => Yii::t('app', 'Upload Quota'),
			'total_quota' => Yii::t('app', 'Total Quota'),
			'sla_nominal' => Yii::t('app', 'Sla Nominal'),
			'sla_upload_exceded' => Yii::t('app', 'Sla Upload Exceded'),
			'sla_total_exceded' => Yii::t('app', 'Sla Total Exceded'),
			'bssPlans' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('quota_profile_id', $this->quota_profile_id);
		$criteria->compare('upload_quota', $this->upload_quota, true);
		$criteria->compare('total_quota', $this->total_quota, true);
		$criteria->compare('sla_nominal', $this->sla_nominal);
		$criteria->compare('sla_upload_exceded', $this->sla_upload_exceded);
		$criteria->compare('sla_total_exceded', $this->sla_total_exceded);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}