<?php

/**
 * This is the model base class for the table "quota_extra".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "QuotaExtra".
 *
 * Columns in table "quota_extra" available as properties of the model,
 * followed by relations of table "quota_extra" available as properties of the model.
 *
 * @property integer $extra_id
 * @property integer $terminal
 * @property integer $status
 * @property integer $traffic_type
 * @property string $quota
 * @property string $initial_consumption
 * @property string $consumed_quota
 * @property string $booking_date
 * @property string $activation_date
 * @property string $completion_date
 * @property string $expiration_date
 * @property integer $notification_total
 *
 * @property QuotaExtraStatus $status0
 * @property Terminal $terminal0
 * @property QuotaExtraTrafficType $trafficType
 */
abstract class BaseQuotaExtra extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'quota_extra';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'QuotaExtra|QuotaExtras', $n);
	}

	public static function representingColumn() {
		return 'booking_date';
	}

	public function rules() {
		return array(
			array('terminal', 'required'),
			array('terminal, status, traffic_type, notification_total', 'numerical', 'integerOnly'=>true),
			array('quota, initial_consumption, consumed_quota', 'length', 'max'=>20),
			array('booking_date, activation_date, completion_date, expiration_date', 'safe'),
			array('status, traffic_type, quota, initial_consumption, consumed_quota, booking_date, activation_date, completion_date, expiration_date, notification_total', 'default', 'setOnEmpty' => true, 'value' => null),
			array('extra_id, terminal, status, traffic_type, quota, initial_consumption, consumed_quota, booking_date, activation_date, completion_date, expiration_date, notification_total', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'status0' => array(self::BELONGS_TO, 'QuotaExtraStatus', 'status'),
			'terminal0' => array(self::BELONGS_TO, 'Terminal', 'terminal'),
			'trafficType' => array(self::BELONGS_TO, 'QuotaExtraTrafficType', 'traffic_type'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'extra_id' => Yii::t('app', 'Extra'),
			'terminal' => null,
			'status' => null,
			'traffic_type' => null,
			'quota' => Yii::t('app', 'Quota'),
			'initial_consumption' => Yii::t('app', 'Initial Consumption'),
			'consumed_quota' => Yii::t('app', 'Consumed Quota'),
			'booking_date' => Yii::t('app', 'Booking Date'),
			'activation_date' => Yii::t('app', 'Activation Date'),
			'completion_date' => Yii::t('app', 'Completion Date'),
			'expiration_date' => Yii::t('app', 'Expiration Date'),
			'notification_total' => Yii::t('app', 'Notification Total'),
			'status0' => null,
			'terminal0' => null,
			'trafficType' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('extra_id', $this->extra_id);
		$criteria->compare('terminal', $this->terminal);
		$criteria->compare('status', $this->status);
		$criteria->compare('traffic_type', $this->traffic_type);
		$criteria->compare('quota', $this->quota, true);
		$criteria->compare('initial_consumption', $this->initial_consumption, true);
		$criteria->compare('consumed_quota', $this->consumed_quota, true);
		$criteria->compare('booking_date', $this->booking_date, true);
		$criteria->compare('activation_date', $this->activation_date, true);
		$criteria->compare('completion_date', $this->completion_date, true);
		$criteria->compare('expiration_date', $this->expiration_date, true);
		$criteria->compare('notification_total', $this->notification_total);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}